KoreBot Library: kb_test.c File Reference
kb_test.c File Reference
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 15 of file kb_test.c.
References kb_config_exit(), kb_config_init(), kb_lookup_device(), kb_msg(), and kb_set_debug_level().