KoreBot Library: kb_gripper.h File Reference
kb_gripper.h File Reference
Defines
#define KGRIPPER_ORDER_MASK
#define ARM_VERSION 0x30
#define ARM_POSITION 0x31
#define ARM_SPEED 0x33
#define ARM_CURRENT 0x34
#define ARM_ON_TARGET 0x36
#define ARM_VOLTAGE 0x37
#define ARM_CAPACITY 0x39
#define ARM_MAX_POSITION 0x3A
#define ARM_MIN_POSITION 0x3C
#define ARM_ORDER 0x3E
#define ARM_MAX_SPEED 0x40
#define ARM_SEARCH_LIMIT 0x41
#define GRIPPER_VERSION 0x30
#define GRIPPER_POSITION 0x31
#define GRIPPER_ORDER 0x32
#define GRIPPER_SPEED 0x33
#define GRIPPER_CURRENT 0x34
#define GRIPPER_TORQUE 0x36
#define GRIPPER_RESISTIVITY 0x38
#define GRIPPER_AMB_IR_LEFT 0x3A
#define GRIPPER_AMB_IR_RIGHT 0x3C
#define GRIPPER_DIST_IR_LEFT 0x3E
#define GRIPPER_DIST_IR_RIGHT 0x40
#define GRIPPER_OPTICAL_BARR 0x42
#define GRIPPER_ON_TARGET 0x43
#define GRIPPER_SEARCH_LIMIT 0x44
#define GRIPPER_MAX_POSITION 0x45
Functions
int kgripper_init (void)
unsigned char kgripper_Arm_Get_Version (knet_dev_t *dev)
unsigned short kgripper_Arm_Get_Position (knet_dev_t *dev)
unsigned char kgripper_Arm_Get_Speed (knet_dev_t *dev)
unsigned short kgripper_Arm_Get_Current (knet_dev_t *dev)
unsigned char kgripper_Arm_OnTarget (knet_dev_t *dev)
unsigned short kgripper_Arm_Get_Voltage (knet_dev_t *dev)
unsigned char kgripper_Arm_Get_Capacity (knet_dev_t *dev)
void kgripper_Arm_Get_Limits (knet_dev_t *dev, unsigned short *Min_Position, unsigned short *Max_Position)
unsigned short kgripper_Arm_Get_Order (knet_dev_t *dev)
unsigned char kgripper_Arm_Get_Max_Speed (knet_dev_t *dev)
unsigned char kgripper_Arm_Get_Search_Limit (knet_dev_t *dev)
void kgripper_Arm_Set_Order (knet_dev_t *dev, unsigned short Order)
void kgripper_Arm_Set_Max_Speed (knet_dev_t *dev, unsigned char Max_Speed)
void kgripper_Arm_Set_Search_Limit (knet_dev_t *dev, unsigned char Search_Limit)
unsigned char kgripper_Gripper_Get_Version (knet_dev_t *dev)
unsigned char kgripper_Gripper_Get_Position (knet_dev_t *dev)
unsigned char kgripper_Gripper_Get_Order (knet_dev_t *dev)
unsigned char kgripper_Gripper_Get_Speed (knet_dev_t *dev)
unsigned short kgripper_Gripper_Get_Current (knet_dev_t *dev)
unsigned short kgripper_Gripper_Get_Torque (knet_dev_t *dev)
unsigned short kgripper_Gripper_Get_Resistivity (knet_dev_t *dev)
void kgripper_Gripper_Get_Ambiant_IR_Light (knet_dev_t *dev, unsigned short *Amb_IR_Left, unsigned short *Amb_IR_Right)
void kgripper_Gripper_Get_Distance_Sensors (knet_dev_t *dev, unsigned short *Dist_IR_Left, unsigned short *Dist_IR_Right)
unsigned char kgripper_Gripper_OnTarget (knet_dev_t *dev)
unsigned char kgripper_Gripper_Object_Detected (knet_dev_t *dev)
unsigned char kgripper_Gripper_Get_Search_Limit (knet_dev_t *dev)
unsigned char kgripper_Gripper_Get_Limits (knet_dev_t *dev)
void kgripper_Gripper_Set_Order (knet_dev_t *dev, unsigned char Order)
void kgripper_Gripper_Set_Torque (knet_dev_t *dev, unsigned short Torque)
void kgripper_GripperSet_Search_Limit (knet_dev_t *dev, unsigned char Search_Limit)
Define Documentation
#define ARM_CAPACITY 0x39
Definition at line 30 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Capacity().
#define ARM_CURRENT 0x34
Definition at line 27 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Current().
#define ARM_MAX_POSITION 0x3A
Definition at line 31 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Limits().
#define ARM_MAX_SPEED 0x40
Definition at line 34 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Max_Speed(), and kgripper_Arm_Set_Max_Speed().
#define ARM_MIN_POSITION 0x3C
Definition at line 32 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Limits().
#define ARM_ON_TARGET 0x36
Definition at line 28 of file kb_gripper.h.
Referenced by kgripper_Arm_OnTarget().
#define ARM_ORDER 0x3E
Definition at line 33 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Order(), and kgripper_Arm_Set_Order().
#define ARM_POSITION 0x31
Definition at line 25 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Position().
#define ARM_SEARCH_LIMIT 0x41
Definition at line 35 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Search_Limit(), and kgripper_Arm_Set_Search_Limit().
#define ARM_SPEED 0x33
Definition at line 26 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Speed().
#define ARM_VERSION 0x30
Definition at line 24 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Version().
#define ARM_VOLTAGE 0x37
Definition at line 29 of file kb_gripper.h.
Referenced by kgripper_Arm_Get_Voltage().
#define GRIPPER_AMB_IR_LEFT 0x3A
Definition at line 48 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Ambiant_IR_Light().
#define GRIPPER_AMB_IR_RIGHT 0x3C
Definition at line 49 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Ambiant_IR_Light().
#define GRIPPER_CURRENT 0x34
Definition at line 45 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Current().
#define GRIPPER_DIST_IR_LEFT 0x3E
Definition at line 50 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Distance_Sensors().
#define GRIPPER_DIST_IR_RIGHT 0x40
Definition at line 51 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Distance_Sensors().
#define GRIPPER_MAX_POSITION 0x45
Definition at line 55 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Limits().
#define GRIPPER_ON_TARGET 0x43
Definition at line 53 of file kb_gripper.h.
Referenced by kgripper_Gripper_OnTarget().
#define GRIPPER_OPTICAL_BARR 0x42
Definition at line 52 of file kb_gripper.h.
Referenced by kgripper_Gripper_Object_Detected().
#define GRIPPER_ORDER 0x32
Definition at line 43 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Order(), and kgripper_Gripper_Set_Order().
#define GRIPPER_POSITION 0x31
Definition at line 42 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Position().
#define GRIPPER_RESISTIVITY 0x38
Definition at line 47 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Resistivity().
#define GRIPPER_SEARCH_LIMIT 0x44
Definition at line 54 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Search_Limit(), and kgripper_GripperSet_Search_Limit().
#define GRIPPER_SPEED 0x33
Definition at line 44 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Speed().
#define GRIPPER_TORQUE 0x36
Definition at line 46 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Torque(), and kgripper_Gripper_Set_Torque().
#define GRIPPER_VERSION 0x30
Definition at line 41 of file kb_gripper.h.
Referenced by kgripper_Gripper_Get_Version().
#define KGRIPPER_ORDER_MASK
Value:
(KNET_ORDER_LITTLE | \
                         KNET_ORDER_REP_ADR | KNET_ORDER_LSB_FIRST )
Definition at line 17 of file kb_gripper.h.
Referenced by kgripper_Arm_Set_Order(), and kgripper_Gripper_Set_Torque().
Function Documentation
unsigned char kgripper_Arm_Get_Capacity (knet_dev_t * dev)
This function return the remaining capacity of the battery
Parameters:
dev K-Net Device Descriptor
Returns:
Capacity Remaining capacity of the battery calculate on the voltage (100% if > 8.2V, 0% if < 6.44V)
Definition at line 161 of file kb_gripper.c.
References ARM_CAPACITY, and knet_read8().
Referenced by status().
unsigned short kgripper_Arm_Get_Current (knet_dev_t * dev)
This function return the actual Current of the Gripper Arm
Parameters:
dev K-Net Device Descriptor
Returns:
Current Position Value from 0 (= 0 mA) to 1023 (= 2000mA)
Definition at line 108 of file kb_gripper.c.
References ARM_CURRENT, and knet_read16().
Referenced by status().
void kgripper_Arm_Get_Limits (knet_dev_t * dev, unsigned short * Min_Position, unsigned short * Max_Position)
This function return the mechanical limit of the gripper
Parameters:
dev K-Net Device Descriptor
Max_Position Maximal position of the arm (ground)
Min_Position Minimal position of the arm (position up)
Definition at line 180 of file kb_gripper.c.
References ARM_MAX_POSITION, ARM_MIN_POSITION, and knet_read16().
Referenced by demo(), get(), searchLimit(), and status().
unsigned char kgripper_Arm_Get_Max_Speed (knet_dev_t * dev)
This function return the maximal speed of the arm
Parameters:
dev K-Net Device Descriptor
Returns:
Max_Speed Maximal speed reach by the arm when moving
Definition at line 218 of file kb_gripper.c.
References ARM_MAX_SPEED, and knet_read8().
Referenced by status().
unsigned short kgripper_Arm_Get_Order (knet_dev_t * dev)
This function return the Position order of the Arm
Parameters:
dev K-Net Device Descriptor
Returns:
order Position Order that the arm must reach
Definition at line 200 of file kb_gripper.c.
References ARM_ORDER, and knet_read16().
Referenced by status().
unsigned short kgripper_Arm_Get_Position (knet_dev_t * dev)
This function return the actual Position of the Gripper Arm
Parameters:
dev K-Net Device Descriptor
Returns:
Position Position Value from 300 (Arm in high position) to 900 (Arm on the ground) These values depend on the mechanical limit of the system. Read the Max_position and Min_position parameters to know the limit position
Definition at line 73 of file kb_gripper.c.
References ARM_POSITION, and knet_read16().
Referenced by status().
unsigned char kgripper_Arm_Get_Search_Limit (knet_dev_t * dev)
This function return the search limit flag
Parameters:
dev K-Net Device Descriptor
Returns:
Search_Limit Flag that indicate if the arm is performing a search of the mechanical limit. Reset when finished.
Definition at line 236 of file kb_gripper.c.
References ARM_SEARCH_LIMIT, and knet_read8().
Referenced by searchLimit().
unsigned char kgripper_Arm_Get_Speed (knet_dev_t * dev)
This function return the actual Speed of the Gripper Arm
Parameters:
dev K-Net Device Descriptor
Returns:
Speed Speed Value, positiv if the arm goes move downwards and negativ if the arm mount
Definition at line 91 of file kb_gripper.c.
References ARM_SPEED, and knet_read8().
Referenced by status().
unsigned char kgripper_Arm_Get_Version (knet_dev_t * dev)
This function return the revision of the Arm Gripper OS
Parameters:
dev K-Net Device Descriptor
Returns:
OSVersion Version (4 MSB) and Revision (4 LSB) of the arm Gripper (Ex: 0xA1)
Definition at line 53 of file kb_gripper.c.
References ARM_VERSION, and knet_read8().
Referenced by revisionOS().
unsigned short kgripper_Arm_Get_Voltage (knet_dev_t * dev)
This function return the Battery Voltage
Parameters:
dev K-Net Device Descriptor
Returns:
Voltage Voltage of the gripper Battery (Vbat = value / 102.4) Ex: 758 = 7.4V
Definition at line 143 of file kb_gripper.c.
References ARM_VOLTAGE, and knet_read16().
Referenced by status().
unsigned char kgripper_Arm_OnTarget (knet_dev_t * dev)
This function return if the arm is on the target or not
Parameters:
dev K-Net Device Descriptor
Returns:
OnTarget Position Flag (1 = Arm on target, 0 = Arm in movement)
Definition at line 126 of file kb_gripper.c.
References ARM_ON_TARGET, and knet_read8().
Referenced by demo(), get(), and status().
void kgripper_Arm_Set_Max_Speed (knet_dev_t * dev, unsigned char Max_Speed)
This function set the maximum speed that the arm can reach
Parameters:
dev K-Net Device Descriptor
Max_Speed Maximal speed from 0 to 15 (default = 5)
Definition at line 271 of file kb_gripper.c.
References ARM_MAX_SPEED, and knet_write8().
Referenced by setMaxSpeed().
void kgripper_Arm_Set_Order (knet_dev_t * dev, unsigned short Order)
This function set a new Position order to reach. If the value is out of the mechanical limit, the gripper will limit itself automatically
Parameters:
dev K-Net Device Descriptor
order Position Order that the arm must reach
Definition at line 254 of file kb_gripper.c.
References ARM_ORDER, KGRIPPER_ORDER_MASK, knet_set_order(), and knet_write16().
Referenced by demo(), get(), and movearm().
void kgripper_Arm_Set_Search_Limit (knet_dev_t * dev, unsigned char Search_Limit)
This function start (=1) or stop (=0) the search limit procedure
Parameters:
dev K-Net Device Descriptor
Search_Limit Flag to start the search limit procedure. reset automatically when the procedure is done
Definition at line 287 of file kb_gripper.c.
References ARM_SEARCH_LIMIT, and knet_write8().
Referenced by searchLimit().
void kgripper_Gripper_Get_Ambiant_IR_Light (knet_dev_t * dev, unsigned short * Amb_IR_Left, unsigned short * Amb_IR_Right)
This function return the ambiant light value of the two IR sensor in the finger
Parameters:
dev K-Net Device Descriptor
Amb_IR_Left Ambiant light value of the sensor in the left finger (0 = no light, 1023 = IR satured of IR light)
Amb_IR_right Ambiant light value of the sensor in the right finger (0 = no light, 1023 = IR satured of IR light)
Definition at line 434 of file kb_gripper.c.
References GRIPPER_AMB_IR_LEFT, GRIPPER_AMB_IR_RIGHT, and knet_read16().
Referenced by sensor().
unsigned short kgripper_Gripper_Get_Current (knet_dev_t * dev)
This function return the actual Current of the Gripper Finger
Parameters:
dev K-Net Device Descriptor
Returns:
Current Current Value from 0 (= 0 mA) to 1023 (= 220mA)
Definition at line 381 of file kb_gripper.c.
References GRIPPER_CURRENT, and knet_read16().
Referenced by demo(), get(), grip(), and status().
void kgripper_Gripper_Get_Distance_Sensors (knet_dev_t * dev, unsigned short * Dist_IR_Left, unsigned short * Dist_IR_Right)
This function return the Distance value measured by the two IR sensor in the finger
Parameters:
dev K-Net Device Descriptor
Dist_IR_Left Distance value of the sensor in the left finger (0 = no object, 1023 = Object very close from the left finger)
Dist_IR_right Distance value of the sensor in the right finger (0 = no object, 1023 = Object very close from the right finger)
Definition at line 456 of file kb_gripper.c.
References GRIPPER_DIST_IR_LEFT, GRIPPER_DIST_IR_RIGHT, and knet_read16().
Referenced by sensor().
unsigned char kgripper_Gripper_Get_Limits (knet_dev_t * dev)
This function return the mechanical limit of the gripper finger
Parameters:
dev K-Net Device Descriptor
Max_Position Maximal position of the Gripper (Open)
Definition at line 532 of file kb_gripper.c.
References GRIPPER_MAX_POSITION, and knet_read8().
Referenced by demo(), get(), grip(), searchLimit(), and status().
unsigned char kgripper_Gripper_Get_Order (knet_dev_t * dev)
This function return the Position order of the Gripper finger
Parameters:
dev K-Net Device Descriptor
Returns:
order Position Order that the gripper must reach
Definition at line 344 of file kb_gripper.c.
References GRIPPER_ORDER, and knet_read8().
Referenced by status().
unsigned char kgripper_Gripper_Get_Position (knet_dev_t * dev)
This function return the actual Position of the Gripper finger
Parameters:
dev K-Net Device Descriptor
Returns:
Position Position Value from 0 (Gripper closed) to ~200 (Gripper open) These values depend on the mechanical limit of the system. Read the Max_position parameters to know the limit position
Definition at line 327 of file kb_gripper.c.
References GRIPPER_POSITION, and knet_read8().
Referenced by status().
unsigned short kgripper_Gripper_Get_Resistivity (knet_dev_t * dev)
This function return the Resistivity of the object grip by the Finger
Parameters:
dev K-Net Device Descriptor
Returns:
Torque Resistivity Value from 0 (= insulator) to 1023 (= conductor)
Definition at line 415 of file kb_gripper.c.
References GRIPPER_RESISTIVITY, and knet_read16().
Referenced by get(), and sensor().
unsigned char kgripper_Gripper_Get_Search_Limit (knet_dev_t * dev)
This function return the search limit flag of the gripper finger
Parameters:
dev K-Net Device Descriptor
Returns:
Search_Limit Flag that indicate if the gripper is performing a search of the mechanical limit. Reset when finished.
Definition at line 515 of file kb_gripper.c.
References GRIPPER_SEARCH_LIMIT, and knet_read8().
Referenced by searchLimit().
unsigned char kgripper_Gripper_Get_Speed (knet_dev_t * dev)
This function return the actual Speed of the Gripper finger
Parameters:
dev K-Net Device Descriptor
Returns:
Speed Speed Value, positiv if the gripper opening and negativ if closing
Definition at line 363 of file kb_gripper.c.
References GRIPPER_SPEED, and knet_read8().
Referenced by status().
unsigned short kgripper_Gripper_Get_Torque (knet_dev_t * dev)
This function return the Torque Limit of the Gripper Finger
Parameters:
dev K-Net Device Descriptor
Returns:
Torque Torque Value from 0 (= 0 mA) to 1023 (= 220mA)
Definition at line 398 of file kb_gripper.c.
References GRIPPER_TORQUE, and knet_read16().
Referenced by grip(), and status().
unsigned char kgripper_Gripper_Get_Version (knet_dev_t * dev)
This function return the revision of the head Gripper OS
Parameters:
dev K-Net Device Descriptor
Returns:
OSVersion Version (4 MSB) and Revision (4 LSB) of the Gripper (Ex: 0xA1)
Definition at line 307 of file kb_gripper.c.
References GRIPPER_VERSION, and knet_read8().
Referenced by revisionOS().
unsigned char kgripper_Gripper_Object_Detected (knet_dev_t * dev)
This function return if an object is between the two finger (use the optical barrier)
Parameters:
dev K-Net Device Descriptor
Returns:
Object Presence of an object flag (0 = no object, 1 = object detected)
Definition at line 496 of file kb_gripper.c.
References GRIPPER_OPTICAL_BARR, and knet_read8().
Referenced by get(), and sensor().
unsigned char kgripper_Gripper_OnTarget (knet_dev_t * dev)
This function return if the Gripper Finger is on the target or not
Parameters:
dev K-Net Device Descriptor
Returns:
OnTarget Position Flag (1 = Gripper on target, 0 = Gripper in movement)
Definition at line 478 of file kb_gripper.c.
References GRIPPER_ON_TARGET, and knet_read8().
Referenced by demo(), get(), grip(), and status().
void kgripper_Gripper_Set_Order (knet_dev_t * dev, unsigned char Order)
This function set a new Position order to reach. If the value is out of the mechanical limit, the gripper will limit itself automatically
Parameters:
dev K-Net Device Descriptor
order Position Order that the gripper finger must reach
Definition at line 550 of file kb_gripper.c.
References GRIPPER_ORDER, and knet_write8().
Referenced by demo(), get(), grip(), and movegrip().
void kgripper_Gripper_Set_Torque (knet_dev_t * dev, unsigned short Torque)
This function set the maximum Torque that the gripper use to grip object
Parameters:
dev K-Net Device Descriptor
Max_Torque Maximal Torque from 100 to 700 (default = 400)
Definition at line 563 of file kb_gripper.c.
References GRIPPER_TORQUE, KGRIPPER_ORDER_MASK, knet_set_order(), and knet_write16().
Referenced by demo(), get(), and setTorque().
void kgripper_GripperSet_Search_Limit (knet_dev_t * dev, unsigned char Search_Limit)
This function start (=1) or stop (=0) the search limit procedure of the gripper
Parameters:
dev K-Net Device Descriptor
Search_Limit Flag to start the search limit procedure. reset automatically when the procedure is done
Definition at line 578 of file kb_gripper.c.
References GRIPPER_SEARCH_LIMIT, and knet_write8().
Referenced by searchLimit().
int kgripper_init (void)
kgripper_init initializes the KoreBot library This function needs to be called BEFORE any other functions.
Parameters:
none
Returns:
A value:
<0 on error
0 on success
Definition at line 28 of file kb_gripper.c.
References KB_ERROR, KB_ERROR_KH3KBINIT, kb_init(), and KH3_ERROR_KBINIT.
Referenced by initGripper().