KoreBot Library: kb_init.c File Reference
kb_init.c File Reference
Functions
int kb_init (int argc, char *argv[])
void kb_exit (void)
Variables
static int kb_init_done = 0
struct option opts []
Function Documentation
void kb_exit (void)
This function is called automatically on exit and call the 'exit' of all sub layer.
Remarks:
This function is called automatically at the terminaison of the application.
Definition at line 74 of file kb_init.c.
References kb_config_exit(), kb_init_done, and knet_exit().
Referenced by kb_init().
int kb_init (int argc, char * argv[])
This function initializes the KoreBot Library
Definition at line 25 of file kb_init.c.
References kb_config_init(), kb_exit(), kb_init_done, kb_msg(), KB_REVISION, kb_set_debug_level(), KB_VERSION, knet_init(), and opts.
Referenced by gpioinit(), kb_lrf_Init(), kb_snd_openDevices(), kgripper_init(), kh3_init(), and main().
Variable Documentation
int kb_init_done = 0 [static]
Definition at line 13 of file kb_init.c.
Referenced by kb_exit(), and kb_init().
struct option opts[]
Initial value:
 {
  { "kb-debug" ,   1 , 0 , 'd' } ,
  { "kb-version" , 1 , 0 , 'v' } ,
  { NULL      ,    0 , 0 , 0    }
}
Definition at line 15 of file kb_init.c.
Referenced by kb_init().