KoreBot Library: kbot.c File Reference
kbot.c File Reference
This module contains all support for the KoreBot board.
Functions
int kbot_SetProcVCore (unsigned int voltage)
int kbot_SetLeds (unsigned char value)
Detailed Description
This module contains all support for the KoreBot board.
This module contains all support for the KoreBot board
Support for the KoreBot board
Author:
Cédric Gaudin (K-Team SA)
Note:
Copyright (C) 2004 K-TEAM SA
Bug:
none discovered.
Todo:
nothing.
Definition in file kbot.c.
Function Documentation
int kbot_SetLeds (unsigned char value)
This function changes the leds connected to I²C on the KoreSDK.
Definition at line 81 of file kbot.c.
References KNET_BUS_ANY, knet_close(), and knet_open().
int kbot_SetProcVCore (unsigned int voltage)
This function changes the VCore voltage of the processor.
Parameters:
voltage required voltage in [mV] (range 600-1400)
Returns:
An error code:
<0 on error
0 on success
Formula used to calculate the Vdac voltage:
, , ,
Definition at line 52 of file kbot.c.
References KB_ERROR, KB_ERROR_OUTOFRANGE, LTC1663_BG, and ltc1663_SendCommand().