KoreBot Library: kmot_monitor.c File Reference
kmot_monitor.c File Reference
Defines
#define MOT_SetPointLL 0x2F
#define timercpy(a, b)
Functions
knet_dev_t * AltMotorOpen (int motor)
knet_dev_t * MotorOpen (int motor)
int main (int argc, char *argv[])
Define Documentation
#define MOT_SetPointLL 0x2F
Definition at line 5 of file kmot_monitor.c.
#define timercpy (a, b)
Value:
(a)->tv_sec = (b)->tv_sec; \
 (a)->tv_usec = (b)->tv_usec;
Definition at line 50 of file kmot_monitor.c.
Function Documentation
knet_dev_t* AltMotorOpen (int motor)
Definition at line 7 of file kmot_monitor.c.
References KNET_BUS_ANY, and knet_open().
int main (int argc, char * argv[])
Definition at line 54 of file kmot_monitor.c.
References kb_init(), kb_set_debug_level(), kmot_GetFWVersion(), kmot_GetMeasure(), kmot_GetStatus(), KMOT_REVISION, kmot_SetOptions(), KMOT_VERSION, kMotMesCurrent, kMotMesPos, kMotMesSpeed, kMotSWOptStopMotorBlk, kMotSWOptWindup, motor, MotorOpen(), position, status(), and timercpy.
knet_dev_t* MotorOpen (int motor)
Definition at line 28 of file kmot_monitor.c.
References KNET_BUS_ANY, and knet_open().