KoreBot Library: kmot_pantilt.c File Reference
kmot_pantilt.c File Reference
Provide a basic test program to control a K-Team pantilt camera with a KoreMotor using the KoreBot library.
Defines
#define MARGIN 20
#define TGT_MARGIN 100
Functions
void InitMotor (knet_dev_t *mot)
knet_dev_t * PantiltOpen (int motor)
int main (int argc, char *argv[])
Detailed Description
Provide a basic test program to control a K-Team pantilt camera with a KoreMotor using the KoreBot library.
K-Team pan-tilt test program
Author:
Pierre Bureau (K-Team SA)
Note:
Copyright (C) 2004 K-TEAM SA
Definition in file kmot_pantilt.c.
Define Documentation
#define MARGIN 20
Definition at line 26 of file kmot_pantilt.c.
Referenced by main().
#define TGT_MARGIN 100
Definition at line 27 of file kmot_pantilt.c.
Referenced by main().
Function Documentation
void InitMotor (knet_dev_t * mot)
Definition at line 29 of file kmot_pantilt.c.
References kmot_ConfigurePID(), kmot_ResetError(), kmot_SetBlockedTime(), kmot_SetLimits(), kmot_SetMargin(), kmot_SetMode(), kmot_SetOptions(), kmot_SetSampleTime(), kmot_SetSpeedProfile(), kMotRegCurrent, kMotRegPos, kMotRegSpeed, kMotSWOptStopMotorBlk, and kMotSWOptWindup.
Referenced by main().
int main (int argc, char * argv[])
Todo:
check args should be rewriten using libpopt
Definition at line 68 of file kmot_pantilt.c.
References InitMotor(), kb_init(), kb_set_debug_level(), kmot_GetFWVersion(), kmot_GetMeasure(), kmot_GetStatus(), KMOT_REVISION, kmot_SearchLimits(), kmot_SetMode(), kmot_SetPoint(), KMOT_VERSION, kMotMesPos, kMotRegPos, kMotRegPosProfile, MARGIN, maxpos0, maxpos1, minpos0, minpos1, motor0, motor1, PantiltOpen(), position, and TGT_MARGIN.
knet_dev_t* PantiltOpen (int motor)
Definition at line 46 of file kmot_pantilt.c.
References KNET_BUS_ANY, and knet_open().
Referenced by main().