KoreBot Library: knet_rs232.h File Reference
knet_rs232.h File Reference
Data Structures
struct knet_rs232_s
Typedefs
typedef struct knet_rs232_s knet_rs232_t
Functions
int knet_rs232_init (knet_bus_t *bus, int argc, char *argv[])
Typedef Documentation
typedef struct knet_rs232_s knet_rs232_t
Function Documentation
int knet_rs232_init (knet_bus_t * bus, int argc, char * argv[])
This function initializes the RS-232 layer.
Parameters:
bus K-Net Bus Descriptor
argc number of elements in argv
argv string used as initialization parameters
Returns:
An error code:
<0 on error - error code
>=0 on success - number of devices found on the bus
Definition at line 63 of file knet_rs232.c.
References knet_bus_s::close, knet_bus_s::exit, knet_rs232_close(), knet_rs232_open(), knet_rs232_read(), knet_rs232_write(), knet_bus_s::open, knet_bus_s::read, knet_bus_s::transfer, and knet_bus_s::write.
Referenced by knet_init().