KoreBot Library: koala_lrf_demo.c File Reference
koala_lrf_demo.c File Reference
Obstacle avoidance program for the Koala robot, using the Led Range Finder.
Defines
#define device "/dev/tts/2"
#define MAX_DIST 2000
#define RCVBUFSIZE 32
Functions
void * koa_lrf_task (void *arg)
void handle_kill (int arg)
int koa_net_stop (int argc, char *argv[])
int koa_net_setspeed (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
int lrf
knet_dev_t * koala
int cmd_received = 0
Detailed Description
Obstacle avoidance program for the Koala robot, using the Led Range Finder.
Led Range Finder Demo
Author:
P.Bureau (K-Team SA)
Note:
Copyright (C) 2005 K-TEAM SA
Bug:
none discovered.
Todo:
Led Range Finder Demo
Author:
P.Bureau (K-Team SA)
Note:
Copyright (C) 2005 K-TEAM SA
Bug:
none discovered.
Todo:
Definition in file koala_lrf_demo.c.
Define Documentation
#define device "/dev/tts/2"
Definition at line 17 of file koala_lrf_demo.c.
#define MAX_DIST 2000
Definition at line 19 of file koala_lrf_demo.c.
Referenced by koa_lrf_task().
#define RCVBUFSIZE 32
Definition at line 20 of file koala_lrf_demo.c.
Function Documentation
void handle_kill (int arg)
Definition at line 128 of file koala_lrf_demo.c.
References kb_lrf_Close(), koa_setSpeed(), and lrf.
void* koa_lrf_task (void * arg)
Definition at line 29 of file koala_lrf_demo.c.
References cmd_received, device, kb_lrf_DistanceData, kb_lrf_GetDistances(), kb_lrf_Init(), koa_setSpeed(), left, lrf, MAX_DIST, and right.
Referenced by main().
int koa_net_setspeed (int argc, char * argv[])
Definition at line 146 of file koala_lrf_demo.c.
References koa_setSpeed(), left, and right.
int koa_net_stop (int argc, char * argv[])
Definition at line 139 of file koala_lrf_demo.c.
References koa_setSpeed().
int main (int argc, char * argv[])
Definition at line 164 of file koala_lrf_demo.c.
References cmd_received, DieWithError(), handle_kill(), kb_init(), kb_set_debug_level(), KNET_BUS_ANY, knet_open(), koa_getOSVersion(), koa_lrf_task(), koa_net_setspeed(), koa_net_stop(), koa_setSpeed(), ksock_add_command(), ksock_exec_command(), ksock_get_command(), ksock_init(), ksock_next_connection(), ksock_server_open(), list_command(), and RCVBUFSIZE.
Variable Documentation
int cmd_received = 0
Definition at line 26 of file koala_lrf_demo.c.
knet_dev_t* koala
Definition at line 24 of file koala_lrf_demo.c.
int lrf
Definition at line 23 of file koala_lrf_demo.c.
Referenced by handle_kill(), and koa_lrf_task().