KoreBot Library: koala.h File Reference
koala.h File Reference
Functions
int koa_getOSVersion (knet_dev_t *dev, unsigned char *version, unsigned char *revision, unsigned char *pversion, unsigned char *prevision)
Function Documentation
int koa_getOSVersion (knet_dev_t * dev, unsigned char * version, unsigned char * revision, unsigned char * pversion, unsigned char * prevision)
This function returns the version of the Koala OS and the protocol revision .
Parameters:
dev K-Net Device Descriptor
Definition at line 51 of file koala.c.
References buf, knet_printf(), and knet_read_string().
Referenced by main().