KoreBot Library: pantilt_demo.c File Reference
pantilt_demo.c File Reference
Demo program to remote control 2 pantilt camera from a wireless ethernet link, using a koremotor to control 2 pantilt.
Defines
#define RCVBUFSIZE 32
Functions
void * koa_init_task (void *arg)
int koa_net_init (int argc, char *argv[])
int koa_net_camera (int argc, char *argv[])
int koa_net_camera2 (int argc, char *argv[])
int koa_net_bothcam (int argc, char *argv[])
int net_exit (int argc, char *argv[])
void InitMotor (knet_dev_t *mot)
int main (int argc, char *argv[])
Variables
knet_dev_t * motor0
knet_dev_t * motor1
knet_dev_t * motor2
knet_dev_t * motor3
int32_t minpos0
int32_t maxpos0
int32_t minpos1
int32_t maxpos1
int32_t minpos2
int32_t maxpos2
int32_t minpos3
int32_t maxpos3
Detailed Description
Demo program to remote control 2 pantilt camera from a wireless ethernet link, using a koremotor to control 2 pantilt.
pantilt demo program (server side)
Author:
Pierre Bureau (K-Team SA)
Note:
Copyright (C) 2004 K-TEAM SA
Definition in file pantilt_demo.c.
Define Documentation
#define RCVBUFSIZE 32
Definition at line 26 of file pantilt_demo.c.
Function Documentation
void InitMotor (knet_dev_t * mot)
Pan-tilt motor initialization
Definition at line 163 of file pantilt_demo.c.
References kmot_ConfigurePID(), kmot_ResetError(), kmot_SetBlockedTime(), kmot_SetLimits(), kmot_SetMargin(), kmot_SetMode(), kmot_SetOptions(), kmot_SetSampleTime(), kmot_SetSpeedProfile(), kMotRegCurrent, kMotRegPos, kMotRegSpeed, kMotSWOptStopMotorBlk, and kMotSWOptWindup.
void* koa_init_task (void * arg)
Koala Camera init task
Definition at line 37 of file pantilt_demo.c.
References kmot_ResetError(), kmot_SearchLimits(), kmot_SetBlockedTime(), maxpos0, maxpos1, maxpos2, maxpos3, minpos0, minpos1, minpos2, and minpos3.
int koa_net_bothcam (int argc, char * argv[])
Definition at line 129 of file pantilt_demo.c.
References kmot_SetPoint(), kMotRegPos, minpos0, minpos1, minpos2, and minpos3.
int koa_net_camera (int argc, char * argv[])
Definition at line 72 of file pantilt_demo.c.
References kmot_SetPoint(), kMotRegPos, kMotRegPosProfile, minpos0, and minpos1.
int koa_net_camera2 (int argc, char * argv[])
Definition at line 103 of file pantilt_demo.c.
References kmot_SetPoint(), kMotRegPos, minpos2, and minpos3.
int koa_net_init (int argc, char * argv[])
Koala Network command callbacks
Definition at line 61 of file pantilt_demo.c.
References KB_ERROR_PTHREAD, KB_FATAL, and koa_init_task().
int main (int argc, char * argv[])
Definition at line 181 of file pantilt_demo.c.
References buf, DieWithError(), InitMotor(), kb_init(), kb_set_debug_level(), kmot_GetFWVersion(), KMOT_REVISION, kmot_SearchLimits(), kmot_SetBlockedTime(), KMOT_VERSION, KNET_BUS_ANY, knet_open(), koa_net_bothcam(), koa_net_camera(), koa_net_camera2(), koa_net_init(), ksock_add_command(), ksock_exec_command(), ksock_get_command(), ksock_init(), ksock_next_connection(), ksock_server_open(), list_command(), maxpos0, maxpos1, maxpos2, maxpos3, minpos0, minpos1, minpos2, minpos3, and RCVBUFSIZE.
int net_exit (int argc, char * argv[])
Definition at line 155 of file pantilt_demo.c.
Variable Documentation
int32_t maxpos0
Definition at line 30 of file pantilt_demo.c.
int32_t maxpos1
Definition at line 30 of file pantilt_demo.c.
int32_t maxpos2
Definition at line 31 of file pantilt_demo.c.
int32_t maxpos3
Definition at line 31 of file pantilt_demo.c.
int32_t minpos0
Definition at line 30 of file pantilt_demo.c.
int32_t minpos1
Definition at line 30 of file pantilt_demo.c.
int32_t minpos2
Definition at line 31 of file pantilt_demo.c.
int32_t minpos3
Definition at line 31 of file pantilt_demo.c.
knet_dev_t* motor0
Definition at line 29 of file pantilt_demo.c.
knet_dev_t * motor1
Definition at line 29 of file pantilt_demo.c.
knet_dev_t * motor2
Definition at line 29 of file pantilt_demo.c.
knet_dev_t * motor3
Definition at line 29 of file pantilt_demo.c.