KoreBot Library: pantilt_demo_client.c File Reference
pantilt_demo_client.c File Reference
Demo program to remote control 2 pantilt camera from a wireless ethernet link. The client reads events from a joystick and send network command to the remote KoreBot.
Defines
#define ACT_KOA 0
#define ACT_CAM1 1
#define ACT_CAM2 2
#define ACT_BOTH 3
#define RCVBUFSIZE 32
Functions
void handle_kill (int arg)
void handle_joyaxis (int number, int value, char *echoBuffer)
void handle_joybutton (int number, int value, char *echoBuffer)
int main (int argc, char *argv[])
Variables
int sendflag = 0
int timeflag = 0
int actionflag = 0
int sock
Detailed Description
Demo program to remote control 2 pantilt camera from a wireless ethernet link. The client reads events from a joystick and send network command to the remote KoreBot.
pantilt demo program (client side)
Author:
Pierre Bureau (K-Team SA)
Note:
Copyright (C) 2004 K-TEAM SA
Definition in file pantilt_demo_client.c.
Define Documentation
#define ACT_BOTH 3
Definition at line 38 of file pantilt_demo_client.c.
#define ACT_CAM1 1
Definition at line 36 of file pantilt_demo_client.c.
#define ACT_CAM2 2
Definition at line 37 of file pantilt_demo_client.c.
#define ACT_KOA 0
Definition at line 35 of file pantilt_demo_client.c.
#define RCVBUFSIZE 32
Definition at line 160 of file pantilt_demo_client.c.
Function Documentation
void handle_joyaxis (int number, int value, char * echoBuffer)
Definition at line 50 of file pantilt_demo_client.c.
References ACT_BOTH, ACT_CAM1, ACT_CAM2, actionflag, ksock_send_command(), sendflag, sock, and timeflag.
void handle_joybutton (int number, int value, char * echoBuffer)
Definition at line 113 of file pantilt_demo_client.c.
References ACT_BOTH, ACT_CAM1, ACT_CAM2, ACT_KOA, actionflag, ksock_send_command(), sendflag, sock, and timeflag.
void handle_kill (int arg)
Definition at line 40 of file pantilt_demo_client.c.
References sock.
int main (int argc, char * argv[])
Definition at line 162 of file pantilt_demo_client.c.
References DieWithError(), fd, handle_joyaxis(), handle_joybutton(), handle_kill(), ksock_connect(), ksock_init(), RCVBUFSIZE, sendflag, sock, and timeflag.
Variable Documentation
int actionflag = 0
Definition at line 32 of file pantilt_demo_client.c.
int sendflag = 0
Definition at line 30 of file pantilt_demo_client.c.
int sock
Definition at line 33 of file pantilt_demo_client.c.
int timeflag = 0
Definition at line 31 of file pantilt_demo_client.c.