KoreBot Library: soundtest.c File Reference
soundtest.c File Reference
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 7 of file soundtest.c.
References FMT_CHUNK_HEADER::bit_per_sample, buf, WAV::fmt, kb_alloc(), kb_free, kb_snd_init(), kb_snd_open(), kb_snd_play(), kb_snd_setSampleRate(), kb_wav_close(), kb_wav_init(), kb_wav_open(), kb_wav_read_data(), FMT_CHUNK_HEADER::nb_channel, and FMT_CHUNK_HEADER::sample_rate.